### ISSUE TITLE
Implement a prismarine-world web visualizer

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-world#17]
It would be cool to be able to see stuff generated in a World instance without having to start minecraft.

Maybe @Creeplays or @dcbartlett already have a part of that ?

Also see https://github.com/vogonistic/mineflayer-voxel

**Comment by rom1504** [comment]
(stuff generated in a world instance include https://github.com/mhsjlw/flying-squid/tree/master/src/lib/worldGenerations and https://github.com/mhsjlw/flying-squid/blob/portal/test/portal_detector.js#L26 )

**Comment by rom1504** [comment]
annoying that the voxeljs api is sync https://github.com/maxogden/voxel-engine#requirevoxel-engineoptions

Way to go around that:
* pregenerate some part of the world, and store it in something then give it to voxeljs
* use https://github.com/PrismarineJS/prismarine-world-sync

**Comment by rom1504** [comment]
about the hacking with voxeljs way, possibilities:
* calling setBlock directly https://github.com/maxogden/voxel-engine/blob/master/index.js#L239

**Comment by rom1504** [comment]
* https://github.com/vogonistic/mineflayer-voxel/pull/1 displays stuff
* https://github.com/voxel/voxel-clientmc is more complete

Would be interesting to take some of the code of one of these and tranform it in a prismarine-world visualizer (that will then be usable along with flying-squid and mineflayer (once mineflayer use prismarine-world), and other more simple application (for example I'd like to display a portal in a web page))

**Comment by rom1504** [comment]
https://github.com/vogonistic/mineflayer-voxel/blob/master/app.js#L258 is a good way to get around voxel sync api

**Comment by rom1504** [comment]
this is pretty cool http://cloud.thomas-edwards.me/mc_test/backup.html

see the page source for more info

**Comment by rom1504** [comment]
(on the browser visualization theme, this is interesting https://www.spigotmc.org/resources/thinkmap.413/, even though the java code won't be usable here ofc)

**Comment by rom1504** [comment]
about a "doesn't take the whole page" visualizer:
> 13:26 < Fudgie> rom1504 yes, its tied to a canvas
> 13:26 < Fudgie> Just resize the canvas element like any old div

**Comment by deathcap** [comment]
> annoying that the voxeljs api is sync https://github.com/maxogden/voxel-engine#requirevoxel-engineoptions

If by sync you mean the `generate` (or `generateVoxelChunk`) options, the alternative is to listen for `missingChunk` events then call `showChunk()` once they are generated, async example: https://github.com/voxel/voxel-land/blob/ee6e1283c606f6c31917ce999de2382058ddcefd/land.js#L122-L133 - this (superior, imho) method is the only one that works in the newer [voxel-engine-stackgl](https://github.com/voxel/voxel-engine-stackgl) currently (a port of voxel-engine using [stack.gl](http://stack.gl) instead of [threejs](http://threejs.org), and solves some inherent problems with the three.js approach, but does not yet have all the features of voxel-engine).

If there are other parts of the API that are sync and making integration difficult, would be happy to change them to async in voxel-engine-stackgl :) let me know

> (on the browser visualization theme, this is interesting https://www.spigotmc.org/resources/thinkmap.413/, even though the java code won't be usable here ofc)

[ThinkMap](https://github.com/thinkofdeath/ThinkMap) is pretty interesting, I contributed some bugfixes a while back, but development has stalled for a while. The server is written in Java, and the client also written in Java but compiles to JavaScript using [GWT](http://www.gwtproject.org/overview.html). 

I think https://github.com/vogonistic/mineflayer-voxel/pull/1 is currently the most promising. @vogonistic @rom1504 what do you about moving mineflayer-voxel into the https://github.com/PrismarineJS organization like https://github.com/PrismarineJS/mineflayer to maintain and develop it there? Would be awesome to get it up and running, actively developed again (it was before my time, I've never tried it until now). 

The approach taken by mineflayer-voxel has some advantages over https://github.com/deathcap/voxel-clientmc - which is more ambitious in that it aims to implement an MC client as the web app itself, whereas mineflayer-voxel runs the "client" (via mineflayer) on a server and uses a simplified custom protocol for communication between the web app and client server. voxel-clientmc is further away from updating to get working again, currently blocked need to update [wsmc](https://github.com/deathcap/wsmc/issues/19) first.

**Comment by rom1504** [comment]
Okay thanks, I'll try the missingChunk then showChunk() approach.

I'm okay with putting mineflayer-voxel in PrismarineJS . https://github.com/vogonistic/mineflayer-voxel/pull/1 only starts to fix things though. I never tested mineflayer-voxel when it was fully working, but I believe there are still things broken in https://github.com/vogonistic/mineflayer-voxel/pull/1 though.

My idea with having a prismarine-world voxel visualizer is that once it's done, it will be possible to use it along with a client (with mineflayer), or with a server directly (with flying-squid), or just load a world and use it without dealing with network problems.
Now it's pretty much WIP because prismarine-world isn't used in mineflayer yet (https://github.com/PrismarineJS/mineflayer/issues/334) and the visualizer is not done at all, so it makes sense to try things in parallel with mineflayer-voxel / voxel-clientmc/... , the more working code the easier it get !

**Comment by rom1504** [comment]
http://cubical.xyz/ is pretty interesting (nothing on github afaik but the source is available (view source))

**Comment by rom1504** [comment]
I stumbled upon http://voxmc.com/vox-populi-web-map/# which is pretty cool too. I wonder if there are any easy to use tiling/map npm module that could be used to display a prismarine-world.

**Comment by rom1504** [comment]
I started some work with voxel+prismarine-world there https://github.com/rom1504/voxel-prismarine-world
It successfully display one chunk in bedrock/air. Currently stuck by https://github.com/voxel/voxel-example/issues/9

**Comment by rom1504** [comment]
on the map theme : https://overviewer.org/ is cool but apparently coded in python and build with a static point of view : 1) read world 2) generate html/js 3) view

**Comment by rom1504** [comment]
would be interesting to provide a tile server for prismarine-world and then use http://leafletjs.com/reference.html#tilelayer to display these tiles.
Not exactly sure how to generate these tiles though.

**Comment by rom1504** [comment]
see https://github.com/andyhall/noa

https://glitch.com/edit/#!/mineweb-dev?path=build%2Flib%2Fmineweb.js%3A4%3A20

https://mineweb.glitch.me/

https://github.com/MinewebMC/mineweb

^ all this could be reused to implement that viewer

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-viewer I'd say this issue is done
More work will get done there
